Delete form-builders css references
academic/vipa pull request #1767
Opened 2017-05-18 13:13 UTC by tugrulcan

Issue #1766
form-builder's v2.2 removes the separate css file see:
https://github.com/kevinchappell/formBuilder/blob/master/CHANGELOG.md

2017-05-18 16:34 UTC, behram requested changes

2017-05-18 16:34 UTC, behram commented on app/config/assetic.yml
> -        - 'https://formbuilder.online/assets/css/form-builder.min.css'
@tugrulcan you thought awesome ;) but, we using this style assets on project. can you replace with existing ones

2017-05-18 17:21 UTC, tugrulcan commented on app/config/assetic.yml
> -        - 'https://formbuilder.online/assets/css/form-builder.min.css'
I added the form-builder under  web/assests/app/css/formBuilder-2.1.2

2017-05-18 17:21 UTC, tugrulcan commented
formbuilder added under web/assests/app/css/formBuilder-2.1.2

2017-05-18 17:46 UTC, tugrulcan commented
@behram please review :)

2017-05-19 10:06 UTC, behram commented
i am testing this pr now.

2017-05-19 11:31 UTC, behram commented
@tugrulcan i used formBuilder bower package beside static assets. thanks for your work. issue resolved with another pr.

related pr;
 - https://github.com/academic/vipa/pull/1768

2017-05-19 11:31 UTC, closed without merging